Revert "[nrf fromtree] Bluetooth: host: Fix undefined reference to ..."
This reverts commit 2294c9a82891a0be6e0694f5b0acd51cbc653181.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>