[nrf fromtree] runners: jlink: Fix NoneType object error
The commit 221199e15b85a070b3d81709eee3d533c9f99967 presents a bug that
makes west flash failed with error.

AttributeError: 'NoneType' object has no attribute 'startswith'

In function is_tunnel(), tunnel may contain None and has no attribute
"startswith". Fix it.

Signed-off-by: Krzysztof Chruściński <krzysztof.chruscinski@nordicsemi.no>
Signed-off-by: Phi Bang Nguyen <phibang.nguyen@nxp.com>
(cherry picked from commit 829c03bcdca378fa2fa55484d16a190d379f754c)