[nrf fromtree] Bluetooth: host: Fix undefined reference to ...
...bt_le_adv_lookup_legacy

Fix undefined referenc to bt_le_adv_lookup_legacy in bt_le_oob_get_local
when bt_le_oob_get_local is used in a central only application.

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>
(cherry picked from commit d1469ecf26d1d98f12942fc2e7174e7f9a5d9c8a)
Signed-off-by: Trond Einar Snekvik <Trond.Einar.Snekvik@nordicsemi.no>