[nrf fromtree] manifest: Update hostap to fix build error
Fix build error of undefined reference to 'inet_aton' in
hostap/src/utils/ip_addr.c

Signed-off-by: Maochen Wang <maochen.wang@nxp.com>
(cherry picked from commit 244958c9f482ab0980da07d7565bd86cca377ed7)