[nrf fromtree] Bluetooth: Host: Fix build error with observer-only config
When building an observer-only build the check_pending_conn label would
result in CI warnings/errors due to this only being a C23 feature:

scan.c:692:1: error: label at end of compound statement is a C23 extension

Turns out the #ifdefs are completely unnecessary, and the code can simply
take advantage of IS_ENABLED(), which should get rid of the warning.

Signed-off-by: Johan Hedberg <johan.hedberg@silabs.com>
(cherry picked from commit 73b6f8bd4a4bde38c8678d750793d02ae3f43c14)
Signed-off-by: Pavel Vasilyev <pavel.vasilyev@nordicsemi.no>